### ISSUE TITLE
Requests to registry hang often

### ISSUE THREAD

**Issue by rosen-vladimirov** [npm/registry-issue-archive#55] opened 2016-09-19 06:57 UTC
Hi,

We are encountering a lot of hang connections to registry.npmjs.org in the last few days. We are working extensively with npm distributed packages and we are currently testing the `@angular` packages. However the requests to registry.npmjs.org hang at some point (different package every time). We've investigated this issue a lot. It first occurred in the middle of August, after that we've changed our configurations to use `http://registry.npmjs.org` instead of `https://registry.npmjs.org` as a registry and this improved the situation. However in the last few days we encounter tons of hanging requests. It's really strange that the connection is in ESTABLISHED state, but it's just hang (checked with TcpView on Windows). If we kill it, the process continues. 
NOTE: The error is reproducible on Mac OS X, Windows and Linux.
After a lot of investigations we can confirm it's not a problem in our internal network. However we've noticed some peaks in our requests when the hang occurs. So we kindly ask for information - is there some limitations of the registry.npmjs.org. For example is there a limitation of the number of requests to registry.npmjs.org from a single public IP?
In case there are no limitations, is there some issue that the registry experience in the last few days?

Do you have any idea what might cause such issues?

**Comment by rosen-vladimirov** [comment] 2016-09-19 07:47
We've also tried working behind a caching proxy and we've received 

```
An error occcured: "connect ETIMEDOUT 151.101.84.162:80", status code "0"
ERR: Error: read ECONNRESET
ERR: Error: read ECONNRESET
ERR: Error: write EPIPE
ERR: Error: write EPIPE
ERR: Error: read ECONNRESET
ERR: Error: read ECONNRESET
```

**Comment by fengmk2** [comment] 2016-09-19 07:52
Can you take a try on the mirror site like https://registry.cnpmjs.org to find out where is the problem? Your internal network or the publick network.

**Comment by soldair** [comment] 2016-09-19 12:27
hello!
we have seen a behavior like this before https://github.com/npm/registry/issues/10 which was actually related to a specific version of nodejs with incorrect http keep-alive pool handling logic. could i have your node and npm versions?

also i would like you to run your installs through https://www.npmjs.com/package/stats-npm  
`npm install -g stats-npm` and `snpm install` instead of `npm install`
this keeps a detailed log file at `./snpm-stats.log` by proxying all of the registry traffic. After capturing and error email this log file to support@npmjs.org and ill be able to dig into it. 

This is an append log so it'll keep getting bigger and bigger so maybe gzip it or truncate it on successful install =)

**Comment by soldair** [comment] 2016-09-19 13:34
ping @rosen-vladimirov

**Comment by rosen-vladimirov** [comment] 2016-09-19 17:23
Hey @soldair , 

I've sent the required logs. Please take a look at them.

**Comment by x-ji** [comment] 2016-09-19 19:57
I'm currently using China Telecom for my connection. I encountered similar issues with the official registry. @fengmk2 's registry (Alibaba's registry) worked fine for me. I think in my case it's just my local ISP not playing very well with the official registry, which occurs frequently with other package systems as well (e.g. Haskell Stack, Elixir Hex). I had to switch mirror for Hex to work as well.

**Comment by tomfrew** [comment] 2016-09-20 11:17
I'm having similar issues to @rosen-vladimirov 
Any suggestions welcome!

**Comment by tomfrew** [comment] 2016-09-22 11:54
I can npm install individual modues but when doing a clean npm install from the package.json it hangs on fetching metadata

**Comment by soldair** [comment] 2016-09-22 12:58
Interesting. Would you please try and install with stats-npm also?

If you do please email support@npmjs.com the stats-npm log and
npm-debug.log (if available) of the failure?

**Comment by tomfrew** [comment] 2016-09-22 15:46
Thanks @soldair. After a bit more testing it's looking like it might be caused by some private modules on an npm enterprise box. We'll do a bit more digging before we send over logs if that's okay?

**Comment by soldair** [comment] 2016-09-22 15:48
ok @tomfrew. ping us at support@ if you need a hand

**Comment by soldair** [comment] 2016-10-18 16:04
ill close this for now but if wecan capture some more useful log data that identifies the ty[pes of errors and requests that failed we can make progress.

**Closed as completed by soldair** 2016-10-18 16:04 UTC
